### PR TITLE
nix docs

### PR DESCRIPTION
**Pull request by micahkendall**

### CODE REVIEW

**Review by rvcas — CHANGES_REQUESTED** [review]
Ah can we not have this in the getting started section actually? That's kinda for tutorials at the moment. What do you think cc @KtorZ, it feels out of place in this section?

**Comment by rvcas** [comment]
Actually I think I've decided this doesn't belong here at all. This is a main repo kinda thing.

**Comment by KtorZ** [comment]
If anywhere, this should be in the _getting-started_ next to `From Source`, have a `From Nix`. 

I was trying the instruction this morning on my machine. Works fine, but I was comparing this with the setup on `Oura` and noticed they used [`crane`](https://github.com/ipetkov/crane) instead of cargo2nix; any thought on that @micahkendall ?

**Comment by micahkendall** [comment]
> Ah can we not have this in the getting started section actually? That's kinda for tutorials at the moment. What do you think cc @KtorZ, it feels out of place in this section?
> I almost want to hide it and bury it at the bottom of the side bar. I do not want to scare people off with Nix and long term this will be development specific documentation not user documentation now that I think about it.
> Actually I think I've decided this doesn't belong here at all. This is a main repo kinda thing.

It could maybe just be deleted entirely. Anyone who uses nix probably will know the commands already.

> If anywhere, this should be in the _getting-started_ page next to `From Source`, have a `From Nix`.
Otherwise, I agree with this.

> I was trying the instruction this morning on my machine. Works fine, but I was comparing this with the setup on `Oura` and noticed they used [`crane`](https://github.com/ipetkov/crane) instead of cargo2nix; any thought on that @micahkendall ?

imo, cargo2nix > crane. Cargo2nix generates real nix, crane is kind of just compatible with nix. Tweag has a blogpost [here](https://www.tweag.io/blog/2022-09-22-rust-nix/) going into it.

**Review by rvcas — APPROVED** [review]

**Pull request merged**
